config { type: "table",
dependencies: ["articles_impressions"]
 }

-- Use the ref() function to manage dependencies.
-- Learn more about ref() and other built in functions here: https://cloud.google.com/dataform/docs/dataform-core

WITH raw AS
(
SELECT
  date,
  EXTRACT(WEEK(SUNDAY) FROM date) AS week_num,
  first_appearance,
  last_appearance,
  Title,
  article_id,
  ai.componenta_name,
  position_in_componenta,
  hp_pageviews,
  seconds_diff / 60 / 60 AS hours_diff,
  ctr,
  -- MAX(ctr) OVER (PARTITION BY date) AS max_ctr_referred_date,
  -- MIN(ctr) OVER (PARTITION BY date) AS min_ctr_referred_date,
  -- MAX(ctr) OVER (PARTITION BY date) - MIN(ctr) OVER (PARTITION BY date) AS scale_range,
  (ctr - MIN(ctr) OVER (PARTITION BY date,ai.componenta_name,ai.position_in_componenta) ) /  (MAX(ctr) OVER (PARTITION BY date) - MIN(ctr) OVER (PARTITION BY date)) AS hour_score,
  s.clicks_percent_from_total AS position_scoring,
  channel,
  minutes_diff,
  seconds_diff,
  clicks,
  average_position_ctr,
  hourly_range
FROM 
  `ynet-data-projects.HP_articles_impressions.articles_impressions` ai JOIN `ynet-data-projects.HP_articles_impressions.hp_positions_scoring` s
  ON ai.componenta_name = s.componenta_name AND ai.position_in_componenta = s.Position
-- WHERE
--   ai.componenta_name = 'סטריפים'
ORDER BY date DESC 
)

, periods_scores AS
(
SELECT 

  r1.date,
  -- MAX measures
  MAX(CASE WHEN r2.date BETWEEN r1.date-6 AND r1.date THEN r2.hp_pageviews * r2.hours_diff * r2.hour_score * r2.position_scoring ELSE NULL END) AS rolling_last7day_max,
  MAX(CASE WHEN r2.date BETWEEN r1.date-30 AND r1.date THEN r2.hp_pageviews * r2.hours_diff * r2.hour_score * r2.position_scoring ELSE NULL END) AS rolling_last30day_max,
  MAX(CASE WHEN r2.date <= r1.date THEN r2.hp_pageviews * r2.hours_diff * r2.hour_score * r2.position_scoring ELSE NULL END) AS all_times_max,
  MAX(CASE WHEN r2.date BETWEEN DATE_TRUNC(r1.date, WEEK(SUNDAY)) AND DATE_ADD(DATE_TRUNC(r1.date, WEEK(SUNDAY)), INTERVAL 6 DAY) THEN r2.hp_pageviews * r2.hours_diff * r2.hour_score * r2.position_scoring ELSE NULL END) AS this_week_max,
  MAX(CASE WHEN r2.date BETWEEN DATE_TRUNC(r1.date, MONTH) AND LAST_DAY(r1.date) THEN r2.hp_pageviews * r2.hours_diff * r2.hour_score * r2.position_scoring ELSE NULL END) AS this_month_max,
  
  -- MIN measures
  MIN(CASE WHEN r2.date BETWEEN r1.date-6 AND r1.date THEN r2.hp_pageviews * r2.hours_diff * r2.hour_score * r2.position_scoring ELSE NULL END) AS rolling_last7day_min,
  MIN(CASE WHEN r2.date BETWEEN r1.date-30 AND r1.date THEN r2.hp_pageviews * r2.hours_diff * r2.hour_score * r2.position_scoring ELSE NULL END) AS rolling_last30day_min,
  MIN(CASE WHEN r2.date <= r1.date THEN r2.hp_pageviews * r2.hours_diff * r2.hour_score * r2.position_scoring ELSE NULL END) AS all_times_min,
  MIN(CASE WHEN r2.date BETWEEN DATE_TRUNC(r1.date, WEEK(SUNDAY)) AND DATE_ADD(DATE_TRUNC(r1.date, WEEK(SUNDAY)), INTERVAL 6 DAY) THEN r2.hp_pageviews * r2.hours_diff * r2.hour_score * r2.position_scoring ELSE NULL END) AS this_week_min,
  MIN(CASE WHEN r2.date BETWEEN DATE_TRUNC(r1.date, MONTH) AND LAST_DAY(r1.date) THEN r2.hp_pageviews * r2.hours_diff * r2.hour_score * r2.position_scoring ELSE NULL END) AS this_month_min

FROM 
  raw r1 CROSS JOIN raw r2 
GROUP BY
  1
)


, scoring AS
(
  SELECT
    *,
    -- hours_diff * hour_score * position_scoring AS final_factor,
    -- hp_pageviews * hours_diff * hour_score * position_scoring AS final_score,
    -- MAX (hp_pageviews * hours_diff * hour_score * position_scoring) OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS rolling_7day_max
    ROUND( ( (hp_pageviews * hours_diff * hour_score * position_scoring) - (s.rolling_last7day_min)  ) / (s.rolling_last7day_max  - s.rolling_last7day_min  ) * 100)  AS rolling_last7day_score,
    ROUND( ( (hp_pageviews * hours_diff * hour_score * position_scoring) - (s.rolling_last30day_min)  ) / (s.rolling_last30day_max  - s.rolling_last30day_min  ) * 100)  AS rolling_last30day_score,
    ROUND( ( (hp_pageviews * hours_diff * hour_score * position_scoring) - (s.this_week_min)  ) / (s.this_week_max  - s.this_week_min  ) * 100)  AS this_week_score,
    ROUND( ( (hp_pageviews * hours_diff * hour_score * position_scoring) - (s.this_month_min) ) / (s.this_month_max - s.this_month_min ) * 100)  AS this_month_score,
    ROUND( ( (hp_pageviews * hours_diff * hour_score * position_scoring) - (s.all_times_min)  ) / (s.all_times_max  - s.all_times_min  ) * 100)  AS all_times_score
  FROM
    raw r LEFT JOIN periods_scores s USING (date)
    -- ON r.article_id = s.article_id
  -- WHERE
    -- position_in_componenta = 0
    -- AND CAST(first_appearance AS STRING) LIKE '%2025-08-30%'
  ORDER BY 
    first_appearance DESC
)

SELECT
  *
FROM
  scoring
